In [14]:
import numpy as np

In [15]:
a = np.array([2,23,4],dtype=np.int64)
print(a.dtype)

int64


In [16]:
a = np.array([2,23,4],dtype=np.float64)
print(a.dtype)

float64


In [17]:
a = np.array([[2,23,4],
              [2,32,4]])
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [18]:
# 全 0 矩阵
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# 全 1 的矩阵
a = np.ones((3,4),dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
# 
a = np.empty((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# 10-20 步长为2
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [28]:
# 3行4列 从 0 到 11
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
a = np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [30]:
a = np.linspace(1,10,6).reshape((2,3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
