In [20]:
import numpy as np

In [21]:
a = np.array([10,20,30,40])

In [22]:
b = np.arange(4)
print(b)

[0 1 2 3]


In [23]:
# 矩阵减法
c = a - b
print(c)

[10 19 28 37]


In [24]:
# 矩阵加法
c = a + b
print(c)

[10 21 32 43]


In [25]:
# 每个元素平方
c = b ** 2
print(c)

[0 1 4 9]


In [26]:
c = 10 * np.sin(a)
print(c)
c = 10 * np.cos(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[-8.39071529  4.08082062  1.5425145  -6.66938062]


In [27]:
# 判断每个元素的大小
print(b)
print(b<3)
print(b==3)

[0 1 2 3]
[ True  True  True False]
[False False False  True]


In [28]:
# 矩阵乘法 (对应元素相乘)
c = a * b
print(c)

[  0  20  60 120]


In [34]:
# 矩阵的乘法
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)
# 点乘
c_dot = np.dot(a,b)
print('-------------')
print(c_dot)
print('-------------')
c_dot_2 = a.dot(b)
print(c_dot_2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
-------------
[[2 4]
 [2 3]]
-------------
[[2 4]
 [2 3]]


In [37]:
a = np.random.random((2,4))
print(a)
# 求和
print(np.sum(a))
# 最小值
print(np.min(a))
# 最大值
print(np.max(a))


[[0.17052498 0.53648256 0.75687183 0.47886764]
 [0.50416749 0.39783335 0.80130494 0.97369595]]
4.619748745283758
0.17052497715915083
0.9736959528030781


In [40]:
a = np.random.random((2,4))
print(a)
print('-------------')
# 求和(每一行求和)
print(np.sum(a,axis=1))
# 最小值(每一列求最小)
print(np.min(a,axis=0))
# 最大值(每一行求最大)
print(np.max(a,axis=1))


[[0.51777251 0.76694372 0.65109339 0.705105  ]
 [0.72827823 0.79992275 0.69583531 0.75767525]]
-------------
[2.64091462 2.98171153]
[0.51777251 0.76694372 0.65109339 0.705105  ]
[0.76694372 0.79992275]
