In [86]:
import torch
import numpy as np

In [87]:
t1 = torch.Tensor([1,2,3])

In [88]:
t1

tensor([1., 2., 3.])

In [89]:
array1 = np.arange(12).reshape(3,4)

In [90]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
torch.Tensor(array1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
## 创建空数组

In [93]:
torch.empty(3,4)

tensor([[9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39, 1.0378e-38]])

In [ ]:
## 创建整型数组

In [95]:
torch.randint(low=0,high=3,size=[3,4])

tensor([[0, 1, 0, 0],
        [1, 1, 2, 1],
        [1, 0, 2, 1]])

In [ ]:
## 张量的方法和属性

In [97]:
t1 = torch.Tensor([[[1]]])

In [100]:
t1.item()

1.0

In [101]:
t2 = torch.Tensor([[[1,2]]])

In [104]:
t2.numpy()

array([[[1., 2.]]], dtype=float32)

In [105]:
t2.shape

torch.Size([1, 1, 2])

In [106]:
t2.size(1)

1

In [107]:
t2.view([1,2])

tensor([[1., 2.]])

In [108]:
t2.view([2,-1])

tensor([[1.],
        [2.]])

In [111]:
t2.std()

tensor(0.7071)

In [116]:
t3 = torch.Tensor(np.arange(24)).reshape(2,3,4)

In [117]:
t3

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [119]:
t3.size()

torch.Size([2, 3, 4])

In [121]:
t3.transpose(0,1)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [122]:
t3.permute(0,1,2)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [123]:
t3.permute(1,0,2)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [124]:
t3.permute(1,2,0)

tensor([[[ 0., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])